node {
  def commit_id
  stage('Preparation') {
    checkout scm
    sh 'git rev-parse --short HEAD > .git/commit-id'
    commit_id = readFile('.git/commit-id').trim()
  }
  stage('test') {
    nodejs(nodeJSInstallationName: 'nodejs') {
      sh 'npm install --only=dev'
      sh 'npm test'
    }
  }

  // stage('docker build/push') {
  //   docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
  //     def app = docker.build("ziggy067/docker-nodejs-demo:${commit_id}", '.').push()
  //   }
  // }

  stage('generate lh report') {
    sh 'npx lhci autorun'

    sh 'docker pull browserless/chrome'

    docker.image('browserless/chrome').inside() {
      sh 'echo hello'
    }
  }
}
