node {
  def commit_id
  stage('Preparation') {
    checkout scm
    sh 'git rev-parse --short HEAD > .git/commit-id'
    commit_id = readFile('.git/commit-id').trim()
  }
  stage('test') {
    nodejs(nodeJSInstallationName: 'nodejs') {
      sh 'npm install --only=dev'
      sh 'npm test'
    }
  }

  // stage('docker build/push') {
  //   docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
  //     def app = docker.build("ziggy067/docker-nodejs-demo:${commit_id}", '.').push()
  //   }
  // }

  stage('generate lh report') {
    sh 'docker pull browserless/chrome'

    docker.image('browserless/chrome').inside('-v ${pwd}:/var/nextgen-web-monorep') {
      sh 'npx lhci autorun'
    }

    // sh 'ls .lighthouseci'

    // reportFileName = sh (
    //     basename $(find .lighthouseci -name "*html" -type f -exec ls {} \;)
    // ).trim()

    report_file_name = sh (
      script: 'basename $(find .lighthouseci -type f -name "*.html")',
      returnStdout: true
    ).trim()

    println report_file_name

    publishHTML (target:[
      allowMissing: false,
      alwaysLinkToLastBuild: true,
      keepAll: true,
      reportDir: '.lighthouseci',
      reportFiles: "${report_file_name},
      reportName: 'My Reports',
    ])
  }
}
